name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    # - uses: jakejarvis/s3-sync-action@master
    - name: Uploading to ec2 deployment server
      run: rsync -zhrv ./* ubuntu@15.206.74.210:/home/ubuntu/test
      
    - name: Uploading to s3 Deployment server
      run: aws s3 cp index.html s3://demo-github-bucket
    
      # aws s3api put-object-acl --bucket "$S3_BUCKET" --key index.html --acl public-read
    #env:
       #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
